<h1>Welcome to post #<?= $post_id ?></h1>

<article class="mb-4 container">
  <div class="card text-center ">
    <h4><?= $post['title'] ?></h4>
    <small><?= $post['created_at'] ?></small>
    <p><small>Author: <strong><?= $post['firstname'] ?> <?= $post['lastname'] ?></strong></small></p>
    <a href="?page=page_post&id=<?= $post['id'] ?>"><img id="posts" src="<?= $post['image'] ?>"></a>
    <div class="card-body" id="card">
      <p class="card-text"><?= $post['description'] ?></p>

    </div>
  </div>



  <section style="background-color: #e7effd;"><br>

    <!-- <form class="mb-5" method="POST" action="?page=page_post&id=<?= $post_id ?>">
      <textarea maxlength="255" class="form-control" name="comment" id="comment" placeholder="Add a comment"></textarea>
      <input type="submit" class="btn btn-dark" value="post a comment !">
    </form> -->

    <div class="card mb-3">
            <!-- <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(32).webp" alt="avatar" width="65"
                height="65" /> -->
            <?php foreach ($posts as $post) : ?>
              <div class="card mb-3">
                <div class="card-body">
                  <?php
                  //$post_id = (int)$_GET['id'];
                  //$db = connectDB();
                  //$sql = $db->prepare("SELECT * from comment INNER JOIN contact ON comment.user_id = contact.user_id where post_id= $post_id ORDER BY posted_at DESC");
                  //$sql->execute();
                  //$posts = $sql->fetch(PDO::FETCH_ASSOC);
                  ?>

                  <h5> <?= $post['firstname'] ?> <?= $post['lastname'] ?></h5>
                  <p class="card-text text-muted"><?= $post['posted_at'] ?></p>
                  <p class="card-text pb-3"><?= $post['comments'] ?></p>
                  <!-- <div class="d-flex justify-content-between align-items-center">
                    <div class="d-flex align-items-center">
                      <a href="#!" class="link-muted me-2"><i class="fas fa-thumbs-up me-1"></i>132</a>
                        <a href="#!" class="link-muted"><i class="fas fa-thumbs-down me-1"></i>15</a>
                    </div>
                   <a href="?page=reply" class="link-muted"><i class="fas fa-reply me-1"></i> Reply</a>
                  </div> -->
                </div> 
                </div>
              <?php endforeach; ?>
              <?php if (isRole("ROLE_MEMBER")): ?>
        <form method="POST">
        <div class="col-12">
            <div class="form-floating mb-3">
                <textarea rows="10" maxlength="255" class="form-control" placeholder="Leave a message here" id="comment" name="comment"></textarea>
                <label for="message">Comment</label>
            </div>
        </div>
        <div class="col-12 mb-3">
            <button type="submit" class="btn btn-dark">Send</button>
        </div>
        </form>
    <?php else: ?>   
        <p>You must be <a href="?page=contact">registered</a> and <a href="?page=login">connected</a> as a member in order to post comments.</p>
    <?php endif ?>
              </div>
  </section>
</article>