<h1>all members</h1>

<?php foreach ($members as $member) : ?>

<article class="text-center mb-4">
    <div class="card">
        <h4>member: <strong><?= $member['firstname'] ?> <?= $member['lastname'] ?></h4>        
        <p><small>id <?= $member['id'] ?></strong></small></p>
        <small><?= $member['registred_at'] ?></small>
        <!-- <a href="?page=page_post&id=<?= $member['id'] ?>"><img id="posts" src="<?= $member['image'] ?>"></a> -->
        <div class="card-body" id="card">
            <a href="?page=update_description&id=<?= $member['id'] ?>" class="btn btn-dark">add a description</a>
            <p class="card-text"><?= $member['message'] ?></p> <br>
            <a class="btn btn-danger" href="javascript:deletePost(<?=$post['id'];?>)" role="button">delete</a>
        </div>
    </div>
</article>

<?php endforeach ?>

<script>
  function deletePost(id){
    const question = window.confirm("are you sure you want to delete this post "+$member['id']+"?");
    if (question === true) {
        location.href="?page=profiles";
    } else {
        return false;
    }  
  }
</script>