<h1>admin dashboard</h1>
<br>
<style>
  img.thumbnail{
    width: 100px;
  }
</style>
<h2 class="text-center m-4">dashboard</h2>
<p><a href="?page=admin_post_add" type="button" class="btn btn-outline-success m-3">add a new post</a></p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Image</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Created At</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($posts as $post) : ?>
    <tr>
      <th scope="row"><?= $post['id']; ?></th>
      <td><img src="<?= $post['image']; ?>"alt="<?= $post['title']?>" width="100" class="thumbnail"></td>
      <td><?= $post['title']; ?></td>
      <td><?= substr($post['description'],0,40); ?>...</td>
      <td><?= $post['created_at']; ?></td>
      <td><a class="btn btn-info" href="?page=admin_post_update&id=<?=$post['id'];?>" role="button">update</a> <br>
      
      <a class="btn btn-danger" href="javascript:deletePost(<?=$post['id'];?>)" role="button">delete</a></td>
    </tr>      
    <?php endforeach; ?>   
  </tbody>
</table>
<p><a href="?page=admin_post_add" type="button" class="btn btn-outline-success m-3">add a new post</a></p>
<script>
  function deletePost(id){
    const question = window.confirm("are you sure you want to delete this post "+id+"?");
    if (question === true) {
        location.href="?page=admin_post_delete&id=" + id ;
    } else {
        return false;
    }  
  }
</script>